Retry API call on 500 error
lifinance/sdk pull request #116
Opened 2023-02-20 07:46 UTC by Abhikumar98

Adding a 1 retry policy for API calls with 500 error code

2023-02-20 10:49 UTC, Abhikumar98 commented on src/utils/errors.ts
> +    this.status = response.status
replace the `response.status` with `response.code`

2023-02-20 10:51 UTC, Addminus requested changes

2023-02-20 10:52 UTC, Addminus commented
retry logic seems fine

2023-02-20 11:03 UTC, Addminus commented
solution looks alright to me, @chybisov pls check if you find something

2023-02-20 11:34 UTC, chybisov commented
Do we want to have a delay between retries? ~~This looks so wrong to me. Maybe we should fix the API in the first place and not make a second request in the hope of success~~ 😅

2023-02-20 11:53 UTC, Abhikumar98 commented
> Do we want to have a delay between retries? ~This looks so wrong to me. Maybe we should fix the API in the first place and not make a second request in the hope of success~ 😅

haha, these are for the times if the DEX responses are throwing 500.

I'll add a delay, how does 500ms sound?

2023-02-21 12:49 UTC, chybisov commented
> > Do we want to have a delay between retries? ~This looks so wrong to me. Maybe we should fix the API in the first place and not make a second request in the hope of success~ 😅
> 
> haha, these are for the times if the DEX responses are throwing 500.
> 
> I'll add a delay, how does 500ms sound?

Yeah, but I mean backend should handle this 🙂

2023-02-21 13:04 UTC, Abhikumar98 commented
> 



> > > Do we want to have a delay between retries? ~This looks so wrong to me. Maybe we should fix the API in the first place and not make a second request in the hope of success~ 😅
> > 
> > 
> > haha, these are for the times if the DEX responses are throwing 500.
> > I'll add a delay, how does 500ms sound?
> 
> Yeah, but I mean backend should handle this 🙂

Ideally yeah, backend should be handling this, since this is majorly with respect to DEX calls failing, we can move this retry logic to backend itself, and not showing an error in frontend.

2023-02-21 15:36 UTC, Addminus commented
I fear that moving this retry logic to the backend might result in timeout errors in the frontend as the logic of checking some status enpoint from dexes and bridges is expensive.

2023-02-22 15:58 UTC, Abhikumar98 commented
> I fear that moving this retry logic to the backend might result in timeout errors in the frontend as the logic of checking some status enpoint from dexes and bridges is expensive and takes time. Adding a delay is a good idea, 500ms is a good starting point.

yep, this does makes sense. Requests can result in timeout, in this case does it makes sense to have the retry logic in place just for the api calls related to DEX and bridges endpoints?

wdyt @chybisov @Addminus ?

PS: Trying to be sure of logic or any other change involved before making the fetch changes overall in the codebase.

2023-02-23 04:56 UTC, chybisov commented
> > I fear that moving this retry logic to the backend might result in timeout errors in the frontend as the logic of checking some status enpoint from dexes and bridges is expensive and takes time. Adding a delay is a good idea, 500ms is a good starting point.
> 
> yep, this does makes sense. Requests can result in timeout, in this case does it makes sense to have the retry logic in place just for the api calls related to DEX and bridges endpoints?
> 
> wdyt @chybisov @Addminus ?
> 
> PS: Trying to be sure of logic or any other change involved before making the fetch changes overall in the codebase.

Let's create a wrapper function for all our fetch requests as per the initial plan not to overthink this. And please give it some small general name like `request` because we can decide to add some other functionality to it in the future (sorry, `lifiFetch` looks ugly to me 😅).

2023-02-23 08:15 UTC, Abhikumar98 commented
> > > I fear that moving this retry logic to the backend might result in timeout errors in the frontend as the logic of checking some status enpoint from dexes and bridges is expensive and takes time. Adding a delay is a good idea, 500ms is a good starting point.
> > 
> > yep, this does makes sense. Requests can result in timeout, in this case does it makes sense to have the retry logic in place just for the api calls related to DEX and bridges endpoints?
> > 
> > wdyt @chybisov @Addminus ?
> > 
> > PS: Trying to be sure of logic or any other change involved before making the fetch changes overall in the codebase.
> 
> Let's create a wrapper function for all our fetch requests as per the initial plan not to overthink this. And please give it some small general name like `request` because we can decide to add some other functionality to it in the future (sorry, `lifiFetch` looks ugly to me 😅). 

Cool got it. Variable naming isn't my best game so it's cool, haha.

2023-03-06 10:14 UTC, Abhikumar98 commented on src/services/ApiService.unit.spec.ts
> +          expect(mockedFetch).toHaveBeenCalledTimes(2)
it's a ServerError with a errorCode of 500. This PR deals with changes which would call this API twice being 500 error

2023-03-06 10:57 UTC, Abhikumar98 commented on src/services/ApiService.unit.spec.ts
> +          expect(mockedFetch).toHaveBeenCalledTimes(2)
There isn't a common argument interface being shared among the functions, hence it's gonna be an additional argument in a handful of them while others would be done by adding a variable in the argument interface.


We are anyways mocking the `fetch` in this scenario and afaik an actual network wouldn't be made in this case.

2023-03-06 11:24 UTC, chybisov commented on src/services/ApiService.unit.spec.ts
> +          expect(mockedFetch).toHaveBeenCalledTimes(2)
No, we should not add any new arguments here. We need to define request settings and adjust them based on the environment - in our case tests. 

Simplified example:

1. Declare `const requestOptions =  { retries: 1 };`
2. In `beforeAll` we set `requestOptions.retries = 0`
3. Run tests...
4. In `afterAll` we set it back `requestOptions.retries = 1`

Maybe you can come up with something better, but this is the way I'd like us to go 😄

2023-03-07 09:51 UTC, chybisov approved these changes

2023-03-07 14:55 UTC, merged