fix: don't trigger chain switch if all actions are done from source chain [LF-1131]
lifinance/sdk pull request #133
Opened 2023-04-12 11:27 UTC by Abhikumar98

# FIX

Switching chains shouldn't be triggered if all actions are done from source chain [LF-1131]

## TL;DR
Disable chain switching if all required actions are already completed on the source chain.

## DESCRIPTION
Currently, the chain switching window is triggered even if all required actions are already completed on the source chain. This can be an unnecessary interruption for users who only need to wait for the tokens to be received in the receiving chain.

This feature will disable the chain switching window if all required actions are already completed on the source chain, and the user only needs to wait for the tokens to be received in the receiving chain.

## STEPS TO TEST
1. Bridge USDC from Ethereum to Polygon.
2. Switch your chains to a third network, say Binance.
3. Upon starting the process, the chain would be promptly switched to the source chain which is Ethereum.
4. Once the allowance is given and this transaction is signed, all the actions that are required from the source are completed, and now we will have to wait for the tokens to be deposited in the receiving chain.
5. While the screen shows "waiting for the funds to receiving receiving", go ahead and switch chains in Metamask and reload the page.

## EXPECTED RESULTS
Since the source chain actions are all done, there is no need for any further chain switching unless there is a swap to be carried out as a step.

## CHECKLIST
- [ ] I have performed a self-review of my code
- [ ] I have commented the code I wrote to make sure the next developers can understand it
- [ ] I have added tests that cover the new functionality
- [ ] I have made sure that existing tests are still passing

2023-04-12 11:38 UTC, Addminus requested changes

2023-04-12 11:39 UTC, Addminus commented on src/execution/StepExecutor.ts
> +      return step
Have you checked if the transaction ever finishes successfully?

2023-04-12 12:09 UTC, Abhikumar98 commented on src/execution/StepExecutor.ts
> +      return step
ahh got it.
I well it finished but the finished transaction wasn't the reloaded page.

I see the mistake, I'm returning before the step execution starts. Fixing it!

2023-04-17 10:10 UTC, Abhikumar98 commented on src/execution/StepExecutor.ts
> +      return step
@Addminus I've fixed this. Please check it out once again.

2023-04-24 15:14 UTC, Addminus approved these changes

2023-04-24 15:36 UTC, merged

2023-04-25 05:49 UTC, chybisov commented
@Abhikumar98 please add tests for this :)