fix(nxtp): on timeout, check historical transactions and restart
lifinance/sdk pull request #23
Opened 2022-01-17 15:08 UTC by mathiasmoeller

- feat: improve handling of wallet & backend errors
- fix(nxtp): on timeout, check historical transactions and restart

2022-01-17 15:09 UTC, mathiasmoeller commented
Rebased on #22

2022-01-19 09:13 UTC, Addminus requested changes
There are multiple typos in test files, all while expecting the same error. That means the typo is somewhere in the codebase

2022-01-19 09:13 UTC, Addminus commented on src/Lifi.unit.spec.ts
> +          'Invalid Routs Request'
typo: Routes

2022-01-19 09:13 UTC, Addminus commented on src/Lifi.unit.spec.ts
> +          'Invalid Routs Request'
typo: Routes

2022-01-19 09:13 UTC, Addminus commented on src/Lifi.unit.spec.ts
> +          'Invalid Routs Request'
typo: Routes

2022-01-19 09:13 UTC, Addminus commented on src/Lifi.unit.spec.ts
> +          'Invalid Routs Request'
typo: Routes

2022-01-19 09:13 UTC, Addminus commented on src/Lifi.unit.spec.ts
> +          'Invalid Routs Request'
typo: Routes

2022-01-19 09:13 UTC, Addminus commented on src/Lifi.unit.spec.ts
> +          'Invalid Routs Request'
typo: Routes

2022-01-26 17:19 UTC, maxklenk approved these changes

2022-01-26 17:20 UTC, merged